update from upstream

diff --git a/contrib/make_tgz b/contrib/make_tgz
--- a/contrib/make_tgz
+++ b/contrib/make_tgz
@@ -20,12 +20,12 @@ fi
 (
     cd "$ROOT_FOLDER"
 
-    echo "'git clean -fx' would delete the following files: >>>"
-    git clean -fx --dry-run
+    echo "'git clean -fd' would delete the following files: >>>"
+    git clean -fd --dry-run
     echo "<<<"
 
     # we could build the kivy atlas potentially?
-    #(cd actilectrum/gui/kivy/; make theming) || echo "building kivy atlas failed! skipping."
+    #(cd electrum/gui/kivy/; make theming) || echo "building kivy atlas failed! skipping."
 
     python3 setup.py --quiet sdist --format=zip,gztar
 )
