moved icons

diff --git a/contrib/osx/make_osx b/contrib/osx/make_osx
--- a/contrib/osx/make_osx
+++ b/contrib/osx/make_osx
@@ -4,8 +4,8 @@
 PYTHON_VERSION=3.6.4
 BUILDDIR=/tmp/actilectrum-build
 PACKAGE=Actilectrum
-GIT_REPO=https://github.com/Actinium-project/actilectrum
-LIBSECP_VERSION=452d8e4d2a2f9f1b5be6b02e18f1ba102e5ca0b4
+GIT_REPO=https://github.com/Actinium-project/Actilectrum
+LIBSECP_VERSION="b408c6a8b287003d1ade5709e6f7bc3c7f1d5be7"
 
 . $(dirname "$0")/base.sh
 
@@ -48,8 +48,17 @@ pyenv global $PYTHON_VERSION || \
 fail "Unable to use Python $PYTHON_VERSION"
 
 
+info "install dependencies specific to binaries"
+brew install openssl
+export CFLAGS="-I$(brew --prefix openssl)/include $CFLAGS"
+export LDFLAGS="-L$(brew --prefix openssl)/lib $LDFLAGS"
+# note that this also installs pinned versions of both pip and setuptools
+python3 -m pip install -Ir ./contrib/deterministic-build/requirements-binaries.txt --user \
+    || fail "Could not install pyinstaller"
+
+
 info "Installing pyinstaller"
-python3 -m pip install -I --user pyinstaller==3.4 || fail "Could not install pyinstaller"
+python3 -m pip install -I --user pyinstaller==3.4 --no-use-pep517 || fail "Could not install pyinstaller"
 
 info "Using these versions for building $PACKAGE:"
 sw_vers
@@ -66,7 +75,6 @@ rm  -rf $BUILDDIR > /dev/null 2>&1
 mkdir $BUILDDIR
 
 cp -R ./contrib/deterministic-build/actilectrum-locale/locale/ ./actilectrum/locale/
-cp    ./contrib/deterministic-build/actilectrum-icons/icons_rc.py ./actilectrum/gui/qt/
 
 
 info "Downloading libusb..."
@@ -99,8 +107,7 @@ DoCodeSignMaybe "CalinsQRReader.app" "${d}/build/Release/CalinsQRReader.app" "$A
 
 
 info "Installing requirements..."
-python3 -m pip install -Ir ./contrib/deterministic-build/requirements.txt --user && \
-python3 -m pip install -Ir ./contrib/deterministic-build/requirements-binaries.txt --user || \
+python3 -m pip install -Ir ./contrib/deterministic-build/requirements.txt --user || \
 fail "Could not install requirements"
 
 info "Installing hardware wallet requirements..."
@@ -108,7 +115,7 @@ python3 -m pip install -Ir ./contrib/deterministic-build/requirements-hw.txt --u
 fail "Could not install hardware wallet requirements"
 
 info "Building $PACKAGE..."
-python3 setup.py install --user > /dev/null || fail "Could not build $PACKAGE"
+python3 -m pip install --user . > /dev/null || fail "Could not build $PACKAGE"
 
 info "Faking timestamps..."
 for d in ~/Library/Python/ ~/.pyenv .; do
